# Generated by Django 4.0.5 on 2022-06-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Konnectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='f_name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='f_name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
