# Generated by Django 4.0.5 on 2022-06-23 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Konnectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('role_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(default='default-img.jpg', upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('website', models.URLField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_distributor', models.CharField(blank=True, max_length=255, null=True)),
                ('p_image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('locale', models.CharField(blank=True, max_length=25)),
                ('title', models.CharField(max_length=200, null=True)),
                ('contact', models.EmailField(blank=True, max_length=255)),
                ('social_link', models.URLField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
