# Generated by Django 4.0.5 on 2022-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Konnectapp', '0004_rename_location_profile_country_alter_profile_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
